name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  complete-example:
    uses: ayush-cd/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
# Seperate Job for TFlint workflow call
  tf-lint:
    uses: ayush-cd/github-shared-workflows/.github/workflows/tf-lint.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
